---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- openweathermap:
    label: Zagreb #optional
    latitude: 45.815399
    longitude: 15.966568
    units: metric # or imperial
    provider: openweathermap
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1

- resources:
    cpu: false
    memory: true
    disk: /

- search:
    provider: duckduckgo
    target: _blank

- datetime:
    text_size: xl
    format:
      timeStyle: short
      hourCycle: h23
